#!/usr/bin/python
# Copyright (c) 2014 Adafruit Industries
# Author: Tony DiCola

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to deal
# in the Software without restriction, including without limitation the rights
# to use, copy, modify, merge, publish, distribute, sublicense, and/or sell
# copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in all
# copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NONINFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING FROM,
# OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE
# SOFTWARE.

import sys

import Adafruit_DHT

import RPi.GPIO as GPIO

from time import sleep

GPIO.cleanup

fanpin = 18


def setup():
	GPIO.setmode(GPIO.BCM)
	GPIO.setup(fanpin, GPIO.OUT)
	GPIO.setwarnings(False)
	return()

def setPin(mode):
	GPIO.output(fanpin, mode)
	return()

def fanON():
	setPin(True)
	return()

def fanOFF():
	setPin(False)
	return()






# Telling the computer what DHT sensor you are using (what you type in on the command line)
sensor_args = { '11': Adafruit_DHT.DHT11,
                '22': Adafruit_DHT.DHT22,
                '2302': Adafruit_DHT.AM2302 }
if len(sys.argv) == 3 and sys.argv[1] in sensor_args:
    sensor = sensor_args[sys.argv[1]]
    temppin = sys.argv[2]
else:
    print('usage: sudo ./Adafruit_DHT.py [11|22|2302] GPIOpin#')
    print('example: sudo ./Adafruit_DHT.py 2302 4 - Read from an AM2302 connected to GPIO #4')
    sys.exit(1)

# Un-comment the line below to convert the temperature to Fahrenheit.
# temperature = temperature * 9/5.0 + 32

# Note that sometimes you won't get a reading and
# the results will be null (because Linux can't
# guarantee the timing of calls to read the sensor).
# If this happens try again!
#if humidity is not None and temperature is not None:
   # print('Temp={0:0.1f}*  Humidity={1:0.1f}%'.format(temperature, humidity))
# else:
    # print('Failed to get reading. Try again!')
    # sys.exit(1)
    
setup()

while True:
        # Try to grab a sensor reading.  Use the read_retry method which will retry up
        # to 15 times to get a sensor reading (waiting 2 seconds between each retry).
        humidity, temperature = Adafruit_DHT.read_retry(sensor, temppin)
        if temperature >= 25:
                fanON()
                print('Fan is on Temp={0:0.1f}* Humidity={1:0.1f}%'.format(temperature, humidity))
        elif temperature is None:
                print('Failed to get reading. Try again!')
                GPIO.cleanup
                sys.exit(1)   
        elif temperature < 25:
                fanOFF()
                print('Temperature was too low, turning fan off. Temp={0:0.1f}* Humidity={1:0.1f}%'.format(temperature, humidity))
        sleep(3)
GPIO.cleanup()
